# Generated by Django 4.0.4 on 2022-06-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_rename_imagen_avatar_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='restaurante'),
        ),
    ]
