# Generated by Django 4.0.4 on 2022-06-06 01:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0008_restaurante_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='Imagen',
            new_name='imagen',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='autor',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurante',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
